# Generated by Django 4.0 on 2024-02-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка'),
        ),
    ]
