# Generated by Django 4.0 on 2024-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='models_app.ProductAmount', to='models_app.Product', verbose_name='Продукты'),
        ),
    ]
