# Generated by Django 4.0 on 2024-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='models_app.ProductAmount', to='models_app.Product', verbose_name='Продукты'),
        ),
    ]
