# Generated by Django 4.0 on 2024-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Промокод'),
        ),
    ]
