# Generated by Django 4.0 on 2024-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
