# Generated by Django 4.0 on 2024-03-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_currency_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_country', to='models_app.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries_city', to='models_app.city', verbose_name='Город по умолчанию'),
        ),
    ]
