# Generated by Django 4.0 on 2024-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_alter_city_country_alter_country_default_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='countries', to='models_app.Product', verbose_name='Продукты'),
        ),
    ]
