# Generated by Django 4.0 on 2024-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_alter_country_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='cities_product', to='models_app.Product', verbose_name='Продукты'),
        ),
    ]
