# Generated by Django 4.0 on 2024-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_alter_city_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='cities_product', to='models_app.Product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='country',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='countries', to='models_app.Product', verbose_name='Продукты'),
        ),
    ]
