# Generated by Django 4.0 on 2024-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0014_alter_country_options_rename_currency_currency_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.CharField(max_length=30, unique=True, verbose_name='Валюта'),
        ),
    ]
