# Generated by Django 4.0 on 2024-03-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0015_alter_currency_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='currency',
        ),
        migrations.AddField(
            model_name='productprice',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices_city', to='models_app.city', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
