# Generated by Django 4.0 on 2024-03-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0017_remove_country_localization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'city')},
        ),
    ]
