# Generated by Django 4.0 on 2024-03-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0018_alter_productprice_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_city', to='models_app.city', verbose_name='Город'),
        ),
    ]
