# Generated by Django 4.0 on 2024-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0020_alter_city_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='localization',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Локализация'),
        ),
    ]
