# Generated by Django 4.0 on 2024-04-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0022_order_localization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productamount',
            unique_together={('product', 'order')},
        ),
    ]
