CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['http://localhost:3000/']
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000/']
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
