from models_app.models.category.models import Category
from models_app.models.city.models import City
from models_app.models.country.models import Country
from models_app.models.currency.models import Currency
from models_app.models.nurse.models import Nurse
from models_app.models.order.models import Order
from models_app.models.product.models import Product
from models_app.models.product_amount.models import ProductAmount
from models_app.models.product_price.models import ProductPrice
