name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/somebody/ss/domdoctor/
            git pull
            /home/somebody/.local/share/virtualenvs/domdoctor-VaEl9DqM/bin/pipenv sync
            /home/somebody/.local/share/virtualenvs/domdoctor-VaEl9DqM/bin/pipenv run python manage.py collectstatic --noinput
            /home/somebody/.local/share/virtualenvs/domdoctor-VaEl9DqM/bin/pipenv run python manage.py migrate
            sudo systemctl restart gunicorn.service
            sudo systemctl restart supervisor
            sudo systemctl restart nginx

